# Generated by Django 3.1 on 2020-08-24 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rig_choices', models.CharField(blank=True, choices=[('active', 'Active'), ('archieve', 'Archieve')], default='', max_length=20, verbose_name='Active')),
                ('rig_image', models.ImageField(default='images/anc-logo.png', upload_to='images/% Y/% m/% d/')),
                ('document', models.FileField(upload_to='documents/% Y/% m/% d/')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
