# Generated by Django 3.1 on 2020-08-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rig', '0002_auto_20200824_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-rig_date']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='rig_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='rig_choices',
            field=models.CharField(choices=[('active', 'Active'), ('archieve', 'Archieve')], default='active', max_length=20, verbose_name='Active'),
        ),
    ]
