# Generated by Django 3.1 on 2020-08-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rig', '0003_auto_20200824_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rig_choices',
            field=models.CharField(choices=[('active', 'Active'), ('archieve', 'Archieve')], default='active', max_length=20, verbose_name='rig Type'),
        ),
    ]
