# Generated by Django 3.1 on 2020-08-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rig', '0004_auto_20200824_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
