# Generated by Django 3.1 on 2021-08-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rig', '0006_auto_20200827_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
