# Generated by Django 3.1 on 2021-09-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rig', '0007_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
